#
dist: xenial
os:
  - linux
language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - docker --version # print the version for logging
  - docker -v
  - docker-compose -v

script:
  - docker-compose -f docker-compose-build.yaml build --parallel
     
# Tasks to perform after the process is successful. 
# Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
# Push images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push docker-user/frontend
  - docker push docker-user/api-feed
  - docker push docker-user/api-user
  - docker push docker-user/reverseproxy